name: Publish NPM Package

'on':
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Copy dependencies
        run: cp -r src/assets package.json dist/
      - name: Publish to NPM
        run: yarn publish dist/ --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
